# Generated by Django 5.2.14 on 2026-05-06 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('rule_type', models.CharField(choices=[('regex', 'Regular Expression (Secrets/Patterns)'), ('ai_prompt', 'AI System Prompt Instruction'), ('complexity', 'Complexity Threshold')], max_length=50)),
                ('configuration', models.JSONField(help_text='JSON containing rule specifics (e.g., regex pattern, threshold limit)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(help_text='The commit SHA that was reviewed', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_score', models.FloatField(blank=True, help_text='Score out of 100 based on review findings', null=True)),
                ('summary', models.TextField(blank=True, help_text='General summary of the review', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField(help_text='The PR number on GitHub')),
                ('title', models.CharField(max_length=512)),
                ('state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('merged', 'Merged')], default='open', max_length=20)),
                ('author', models.CharField(help_text='GitHub username of the PR author', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path of the file being commented on', max_length=1024)),
                ('line_number', models.IntegerField(blank=True, help_text='Line number in the file (if applicable)', null=True)),
                ('comment_text', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('security', 'Security'), ('style', 'Style/Linting'), ('complexity', 'Complexity'), ('bug', 'Potential Bug'), ('ai_suggestion', 'AI Suggestion')], default='ai_suggestion', max_length=50)),
                ('github_comment_id', models.BigIntegerField(blank=True, help_text='ID of the comment on GitHub if posted', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='review_engine.codereview')),
            ],
        ),
        migrations.AddField(
            model_name='codereview',
            name='pull_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='review_engine.pullrequest'),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(help_text="GitHub's internal ID for the repository", unique=True)),
                ('owner', models.CharField(help_text='Owner of the repository (user or organization)', max_length=255)),
                ('name', models.CharField(help_text='Name of the repository', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='review_engine.repository'),
        ),
        migrations.AlterUniqueTogether(
            name='pullrequest',
            unique_together={('repository', 'pr_number')},
        ),
    ]
